### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by laserlemon**
Hey folks! I love Start Bootstrap and thought you might find this useful. I helped build this service (called [Inchworm](https://inchworm.io)) that automatically optimizes images in GitHub repos, and submit pull requests whenever it finds new images. It's free for open source and all the optimization is lossless.

I ran an optimization so you can see how it works. I'm copying/pasting the summary that Inchworm normally provides below.

If you want, you can sign in with GitHub at [inchworm.io](https://inchworm.io) and all of your images will be monitored and optimized for free in the future. Either way, hope it helps!

Steve

---

## Inchworm Image Optimization Summary

Inchworm optimized 66 images for a total savings of 8.15 KB (0.3%).

| Image | Original | Saved | % |
|:--- | ---:| ---:| ---:|
| assets/img/bg.png | 5.68 KB | 465 B | 8.0% |
| assets/img/gh-pages-logo.png | 882 B | 358 B | 40.6% |
| assets/img/hostoople-logo.png | 2.41 KB | 96 B | 3.9% |
| assets/img/ico/touch-icon-ipad-retina.png | 3.06 KB | 1.67 KB | 54.7% |
| assets/img/ico/touch-icon-ipad.png | 1.47 KB | 741 B | 49.3% |
| assets/img/ico/touch-icon-iphone-retina.png | 2.33 KB | 1.19 KB | 50.8% |
| assets/img/ico/touch-icon-iphone.png | 1.19 KB | 590 B | 48.2% |
| assets/img/maxcdn-logo.png | 1.77 KB | 287 B | 15.9% |
| assets/img/og/startbootstrap-logo.jpg | 6.44 KB | 20 B | 0.3% |
| assets/img/premium-bg.png | 19.1 KB | 1.25 KB | 6.5% |
| assets/img/premium/ace-admin.jpg | 84.6 KB | 39 B | 0.0% |
| assets/img/premium/angle.jpg | 49.7 KB | 62 B | 0.1% |
| assets/img/premium/atropos.jpg | 46.2 KB | 14 B | 0.0% |
| assets/img/premium/boomerang.jpg | 53.9 KB | 25 B | 0.0% |
| assets/img/premium/dashgum.jpg | 41 KB | 14 B | 0.0% |
| assets/img/premium/flat-ui-pro.jpg | 46.1 KB | 4 B | 0.0% |
| assets/img/premium/flatify.jpg | 46.4 KB | 1 B | 0.0% |
| assets/img/premium/flex-admin.jpg | 120 KB | 24 B | 0.0% |
| assets/img/premium/maxfront.jpg | 37 KB | 37 B | 0.1% |
| assets/img/premium/pixel-admin.jpg | 55 KB | 42 B | 0.1% |
| assets/img/premium/porto.jpg | 78.5 KB | 47 B | 0.1% |
| assets/img/premium/reen.jpg | 43.9 KB | 19 B | 0.0% |
| assets/img/premium/singleport.jpg | 49.7 KB | 42 B | 0.1% |
| assets/img/premium/spectrum.jpg | 514 KB | 102 B | 0.0% |
| assets/img/premium/startup-framework-demo-2.jpg | 46.8 KB | 17 B | 0.0% |
| assets/img/premium/startup-framework-home.jpg | 98.5 KB | 2 B | 0.0% |
| assets/img/premium/unify.jpg | 65.9 KB | 32 B | 0.0% |
| assets/img/premium/velocity.jpg | 52.9 KB | 33 B | 0.1% |
| assets/img/premium/vitality.jpg | 231 KB | 47 B | 0.0% |
| assets/img/showcase/abdulla.jpg | 65.3 KB | 23 B | 0.0% |
| assets/img/showcase/buchert-road.jpg | 86.5 KB | 38 B | 0.0% |
| assets/img/showcase/budapest-bank.jpg | 82.7 KB | 54 B | 0.1% |
| assets/img/showcase/charlotte-seaberry.jpg | 50.3 KB | 35 B | 0.1% |
| assets/img/showcase/halil.jpg | 35.3 KB | 21 B | 0.1% |
| assets/img/showcase/jamieweb.jpg | 94.1 KB | 120 B | 0.1% |
| assets/img/showcase/marko.jpg | 33.3 KB | 13 B | 0.0% |
| assets/img/showcase/provolve.jpg | 76.1 KB | 39 B | 0.1% |
| assets/img/showcase/windowface.jpg | 36.1 KB | 29 B | 0.1% |
| assets/img/templates/1-col-portfolio.jpg | 31.9 KB | 35 B | 0.1% |
| assets/img/templates/2-col-portfolio.jpg | 24 KB | 37 B | 0.2% |
| assets/img/templates/3-col-portfolio.jpg | 34.5 KB | 16 B | 0.0% |
| assets/img/templates/bare.jpg | 13.7 KB | 7 B | 0.0% |
| assets/img/templates/blog-home.jpg | 32.9 KB | 5 B | 0.0% |
| assets/img/templates/blog-post.jpg | 50 KB | 13 B | 0.0% |
| assets/img/templates/business-casual.jpg | 64.5 KB | 34 B | 0.1% |
| assets/img/templates/business-frontpage.jpg | 27.8 KB | 15 B | 0.1% |
| assets/img/templates/clean-blog.jpg | 76.2 KB | 13 B | 0.0% |
| assets/img/templates/creative.jpg | 46.1 KB | 58 B | 0.1% |
| assets/img/templates/freelancer.jpg | 29 KB | 27 B | 0.1% |
| assets/img/templates/full-slider.jpg | 13.7 KB | 14 B | 0.1% |
| assets/img/templates/full-width-pics.jpg | 25.8 KB | 32 B | 0.1% |
| assets/img/templates/full.jpg | 11.1 KB | 15 B | 0.1% |
| assets/img/templates/half-slider.jpg | 19.7 KB | 24 B | 0.1% |
| assets/img/templates/landing-page.jpg | 43.9 KB | 11 B | 0.0% |
| assets/img/templates/logo-nav.jpg | 12.8 KB | 24 B | 0.2% |
| assets/img/templates/modern-business.jpg | 34.5 KB | 25 B | 0.1% |
| assets/img/templates/one-page-wonder.jpg | 44.5 KB | 32 B | 0.1% |
| assets/img/templates/portfolio-item.jpg | 23.9 KB | 15 B | 0.1% |
| assets/img/templates/round-about.jpg | 34.1 KB | 7 B | 0.0% |
| assets/img/templates/scrolling-nav.jpg | 13.3 KB | 23 B | 0.2% |
| assets/img/templates/shop-homepage.jpg | 32.7 KB | 40 B | 0.1% |
| assets/img/templates/shop-item.jpg | 34.6 KB | 11 B | 0.0% |
| assets/img/templates/simple-sidebar.jpg | 16.3 KB | 29 B | 0.2% |
| assets/img/templates/small-business.jpg | 35.9 KB | 20 B | 0.1% |
| assets/img/templates/thumbnail-gallery.jpg | 20.4 KB | 16 B | 0.1% |
| assets/img/wrapbootstrap.jpg | 9.07 KB | 18 B | 0.2% |

### CODE REVIEW

**Comment by danog** [comment]
Nice! Implementing it in my repos...

**Comment by laserlemon** [comment]
@danog That's great, just let me know if you have any questions or need help!

**Comment by danog** [comment]
All good, except that I can't log out of the inchworm website on mobile devices.



Website: http://daniil.it

**Comment by laserlemon** [comment]
Thanks for pointing that out! If you tap in the very top right corner of the page, a submenu will open and allow you to log out. A bug is preventing that button from being visible. I'll get that fixed up!

**Comment by danog** [comment]
Goody :)

**Comment by davidtmiller** [comment]
Thanks for offering up these changes! I will get this implemented soon in the next patch.

**Comment by laserlemon** [comment]
:+1:

**Pull request closed without merging**
