### PR TITLE
Add user version to clean-blog

### PR DESCRIPTION
**Pull request by humboldtux**

### CODE REVIEW

**Comment by tamanonymous** [comment]
thanls.

**Comment by humboldtux** [comment]
I've updated this PR to reflect changes done to the file meanwhile.

**Comment by humboldtux** [comment]
Hi David,

Do you want me to update this PR, or is it completly rejected?

**Comment by davidtmiller** [comment]
Hey there! I changed all of the default repositories over to master, so if you want to make a PR into the master branch go ahead!

**Pull request closed without merging**
